project:
  type: book

book:
  title: "Creative Coding with Pure Data"
  author: "Ezequiel Abregú"
  date: "2025-05-11"
  chapters:
    - index.qmd
    - chapters/introduction.qmd
    - chapters/music-scale-generator.qmd
    - chapters/chapter.qmd
    - chapters/conclusion.qmd

#bibliography: references.bib

format:
  html:
    mermaid: {}
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-location: left
    code-copy: true
    code-overflow: wrap
    sidebar: true
    page-layout: full
    lightbox: true

website:
  navbar: false
  page-navigation: true
  repo-url: https://github.com/ezequielabregu/creative-code-with-pd
  repo-actions: [edit, issue]

reference-location: margin
citation-location: margin
caption-location: margin