project:
  type: book

execute:
  freeze: auto

jupyter: python3

book:
  title: "Creative Coding with Pure Data"
  author: "Ezequiel Abregú"
  date: "2025-05-11"

  chapters:
    - index.qmd
    - chapters/introduction.qmd
    - chapters/playrec.qmd
    - chapters/sequencers.qmd
    - chapters/synthesis.qmd
    - chapters/sonification.qmd
    - chapters/tools.qmd
    - chapters/conclusion.qmd
  
  page-footer:
    center: 
    - text: "Creative Coding with Pure Data - Ezequiel Abregú"

  reader-mode: true
  repo-url: https://github.com/ezequielabregu/creative-code-with-pd
  #repo-actions: [issue]
#  sidebar: 
#    #background: "#F5F5F5"
#    logo: /assets/images/index/cover_1.png
#    search: true

bibliography: references.bib

format:
  html:
    mermaid: {}
    theme:
      light: cosmo
      dark: darkly
    toc: true
    #toc-location: left
    code-copy: true
    code-overflow: wrap
    sidebar: true
    page-layout: full
    lightbox: true
    css: styles.css

website:
  navbar: false
  page-navigation: true
  repo-url: https://github.com/ezequielabregu/creative-code-with-pd
  #repo-actions: [edit, issue]



#reference-location: margin
#citation-location: margin
#caption-location: margin