project:
  type: book

execute:
  freeze: auto

jupyter: python3

book:
  title: "Code that Sounds"
  subtitle: "Creative Coding and Sonic Thinking with Pure Data"
  author: "Ezequiel Abregú"
  date: "2025-05-11"

  chapters:
    - index.qmd
    - chapters/introduction.qmd
    - chapters/playrec.qmd
    - chapters/sequencer.qmd
    - chapters/synthesis.qmd
    - chapters/sonification.qmd
    - chapters/space.qmd
    - chapters/conclusion.qmd
    #- chapters/appendix.qmd
    #- chapters/references.qmd
  
  page-footer:
    center: 
    - text: "Code that Sounds - Ezequiel Abregú"

  reader-mode: true
  repo-url: https://github.com/ezequielabregu/code-that-sounds
  #repo-actions: [issue]

#  sidebar: 
#    #background: "#F5F5F5"
#    logo: /assets/images/index/cover-5.png
#    search: true

bibliography: references.bib

format:
  html:
    mermaid: {}
    theme:
      light: cosmo
      dark: darkly
    toc: true
    #toc-location: left
    code-copy: true
    code-overflow: wrap
    sidebar: true
    page-layout: full
    lightbox: true
    css: styles.css

#  pdf:
#    documentclass: scrreprt
#    toc: true
#    number-sections: true

website:
  navbar: false
  page-navigation: true
  #repo-url: https://github.com/ezequielabregu/code-that-sounds
  #repo-actions: [issue]



#reference-location: margin
#citation-location: margin
#caption-location: margin