<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.29">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Sequencers – Creative Coding with Pure Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/synthesis.html" rel="next">
<link href="../chapters/playrec.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-748b535e376f14d4692bf2b2e5fd6380.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1e81d527365e20b3495763033adbcf98.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-8ab8b311eebd604b8865a9cbc6c08092.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-1e81d527365e20b3495763033adbcf98.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="mermaid-theme" content="neutral">
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/sequencers.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Sequencers</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Creative Coding with Pure Data</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/ezequielabregu/creative-code-with-pd" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/playrec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Rec &amp; Play</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sequencers.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Sequencers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/synthesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Synthesis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sonification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sonification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tools</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#arrays-and-sequencers" id="toc-arrays-and-sequencers" class="nav-link active" data-scroll-target="#arrays-and-sequencers"><span class="header-section-number">3.1</span> Arrays and Sequencers</a>
  <ul class="collapse">
  <li><a href="#represent-an-8-step-sequencer-using-pseudo-code" id="toc-represent-an-8-step-sequencer-using-pseudo-code" class="nav-link" data-scroll-target="#represent-an-8-step-sequencer-using-pseudo-code"><span class="header-section-number">3.1.1</span> Represent an 8-step sequencer using pseudo code&nbsp;</a></li>
  <li><a href="#python-implementation-of-the-8-step-sequencer" id="toc-python-implementation-of-the-8-step-sequencer" class="nav-link" data-scroll-target="#python-implementation-of-the-8-step-sequencer"><span class="header-section-number">3.1.2</span> Python Implementation of the 8-Step Sequencer</a></li>
  <li><a href="#represent-a-random-sequencer-using-pseudo-code" id="toc-represent-a-random-sequencer-using-pseudo-code" class="nav-link" data-scroll-target="#represent-a-random-sequencer-using-pseudo-code"><span class="header-section-number">3.1.3</span> Represent a random sequencer using pseudo code</a></li>
  <li><a href="#random-step-sequencer-implementation" id="toc-random-step-sequencer-implementation" class="nav-link" data-scroll-target="#random-step-sequencer-implementation"><span class="header-section-number">3.1.4</span> Random Step Sequencer Implementation</a></li>
  </ul></li>
  <li><a href="#piano-phase-steve-reich" id="toc-piano-phase-steve-reich" class="nav-link" data-scroll-target="#piano-phase-steve-reich"><span class="header-section-number">3.2</span> Piano Phase (Steve Reich)</a>
  <ul class="collapse">
  <li><a href="#piano-phase-process-as-an-algorithm." id="toc-piano-phase-process-as-an-algorithm." class="nav-link" data-scroll-target="#piano-phase-process-as-an-algorithm."><span class="header-section-number">3.2.1</span> Piano Phase process as an algorithm.</a></li>
  <li><a href="#piano-phase-implementation-in-python-single-sequencer" id="toc-piano-phase-implementation-in-python-single-sequencer" class="nav-link" data-scroll-target="#piano-phase-implementation-in-python-single-sequencer"><span class="header-section-number">3.2.2</span> Piano Phase Implementation in Python (single sequencer)</a></li>
  </ul></li>
  <li><a href="#random-melody-generator" id="toc-random-melody-generator" class="nav-link" data-scroll-target="#random-melody-generator"><span class="header-section-number">3.3</span> Random Melody Generator</a>
  <ul class="collapse">
  <li><a href="#patch-overview" id="toc-patch-overview" class="nav-link" data-scroll-target="#patch-overview"><span class="header-section-number">3.3.1</span> Patch Overview</a></li>
  <li><a href="#scale-and-melody-generation" id="toc-scale-and-melody-generation" class="nav-link" data-scroll-target="#scale-and-melody-generation"><span class="header-section-number">3.3.2</span> Scale and Melody Generation</a></li>
  <li><a href="#melody-storage" id="toc-melody-storage" class="nav-link" data-scroll-target="#melody-storage"><span class="header-section-number">3.3.3</span> Melody Storage</a></li>
  <li><a href="#playback-control" id="toc-playback-control" class="nav-link" data-scroll-target="#playback-control"><span class="header-section-number">3.3.4</span> Playback Control</a></li>
  <li><a href="#midi-output" id="toc-midi-output" class="nav-link" data-scroll-target="#midi-output"><span class="header-section-number">3.3.5</span> MIDI Output</a></li>
  <li><a href="#step-by-step-data-flow" id="toc-step-by-step-data-flow" class="nav-link" data-scroll-target="#step-by-step-data-flow"><span class="header-section-number">3.3.6</span> Step-by-Step Data Flow</a></li>
  <li><a href="#key-objects-and-their-roles" id="toc-key-objects-and-their-roles" class="nav-link" data-scroll-target="#key-objects-and-their-roles"><span class="header-section-number">3.3.7</span> Key Objects and Their Roles</a></li>
  <li><a href="#diagram-melody-generation-and-playback" id="toc-diagram-melody-generation-and-playback" class="nav-link" data-scroll-target="#diagram-melody-generation-and-playback"><span class="header-section-number">3.3.8</span> Diagram: Melody Generation and Playback</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">3.3.9</span> Summary</a></li>
  </ul></li>
  <li><a href="#the-euclidean-algorithm-generates-traditional-musical-rhythms" id="toc-the-euclidean-algorithm-generates-traditional-musical-rhythms" class="nav-link" data-scroll-target="#the-euclidean-algorithm-generates-traditional-musical-rhythms"><span class="header-section-number">3.4</span> The Euclidean Algorithm Generates Traditional Musical Rhythms</a>
  <ul class="collapse">
  <li><a href="#summary-1" id="toc-summary-1" class="nav-link" data-scroll-target="#summary-1"><span class="header-section-number">3.4.1</span> Summary</a></li>
  <li><a href="#hypothesis" id="toc-hypothesis" class="nav-link" data-scroll-target="#hypothesis"><span class="header-section-number">3.4.2</span> Hypothesis</a></li>
  <li><a href="#patterns-of-maximal-evenness" id="toc-patterns-of-maximal-evenness" class="nav-link" data-scroll-target="#patterns-of-maximal-evenness"><span class="header-section-number">3.4.3</span> Patterns of Maximal Evenness</a></li>
  <li><a href="#euclidean-algorithm" id="toc-euclidean-algorithm" class="nav-link" data-scroll-target="#euclidean-algorithm"><span class="header-section-number">3.4.4</span> Euclidean Algorithm</a></li>
  <li><a href="#how-does-computing-the-gcd-turn-into-maximally-even-distributed-patterns" id="toc-how-does-computing-the-gcd-turn-into-maximally-even-distributed-patterns" class="nav-link" data-scroll-target="#how-does-computing-the-gcd-turn-into-maximally-even-distributed-patterns"><span class="header-section-number">3.4.5</span> How does computing the GCD turn into maximally even distributed patterns?</a></li>
  <li><a href="#example-13-5" id="toc-example-13-5" class="nav-link" data-scroll-target="#example-13-5"><span class="header-section-number">3.4.6</span> Example (13, 5)</a></li>
  <li><a href="#example-17-7" id="toc-example-17-7" class="nav-link" data-scroll-target="#example-17-7"><span class="header-section-number">3.4.7</span> Example (17, 7)</a></li>
  <li><a href="#implementation-in-pure-data---euclidean-sequencer" id="toc-implementation-in-pure-data---euclidean-sequencer" class="nav-link" data-scroll-target="#implementation-in-pure-data---euclidean-sequencer"><span class="header-section-number">3.4.8</span> Implementation in Pure Data - Euclidean sequencer</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">3.4.9</span> References</a></li>
  </ul></li>
  <li><a href="#cellular-automata" id="toc-cellular-automata" class="nav-link" data-scroll-target="#cellular-automata"><span class="header-section-number">3.5</span> Cellular Automata</a>
  <ul class="collapse">
  <li><a href="#one-dimensional-cellular-automata-1dca" id="toc-one-dimensional-cellular-automata-1dca" class="nav-link" data-scroll-target="#one-dimensional-cellular-automata-1dca"><span class="header-section-number">3.5.1</span> One-Dimensional Cellular Automata (1DCA)</a></li>
  <li><a href="#the-case-of-rule-30" id="toc-the-case-of-rule-30" class="nav-link" data-scroll-target="#the-case-of-rule-30"><span class="header-section-number">3.5.2</span> The Case of Rule 30</a></li>
  <li><a href="#rule-30-implementation-in-python" id="toc-rule-30-implementation-in-python" class="nav-link" data-scroll-target="#rule-30-implementation-in-python"><span class="header-section-number">3.5.3</span> Rule 30 Implementation in Python</a></li>
  <li><a href="#two-dimensional-cellular-automata-2dca" id="toc-two-dimensional-cellular-automata-2dca" class="nav-link" data-scroll-target="#two-dimensional-cellular-automata-2dca"><span class="header-section-number">3.5.4</span> Two-Dimensional Cellular Automata (2DCA)</a></li>
  <li><a href="#case-study-conways-game-of-life" id="toc-case-study-conways-game-of-life" class="nav-link" data-scroll-target="#case-study-conways-game-of-life"><span class="header-section-number">3.5.5</span> Case Study: Conway’s Game of Life</a></li>
  <li><a href="#origins" id="toc-origins" class="nav-link" data-scroll-target="#origins"><span class="header-section-number">3.5.6</span> Origins</a></li>
  <li><a href="#patterns" id="toc-patterns" class="nav-link" data-scroll-target="#patterns"><span class="header-section-number">3.5.7</span> Patterns</a></li>
  <li><a href="#python-implementation-of-game-of-life" id="toc-python-implementation-of-game-of-life" class="nav-link" data-scroll-target="#python-implementation-of-game-of-life"><span class="header-section-number">3.5.8</span> Python Implementation of Game of Life</a></li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading"><span class="header-section-number">3.5.9</span> Further Reading</a></li>
  <li><a href="#interactive-websites" id="toc-interactive-websites" class="nav-link" data-scroll-target="#interactive-websites"><span class="header-section-number">3.5.10</span> Interactive Websites</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Sequencers</span></h1>
</div>



<div class="quarto-title-meta column-body">

    
  
    
  </div>
  


</header>


<p>In this chapter, we will explore the concept of sequencers and how they can be implemented in Pure Data.</p>
<section id="arrays-and-sequencers" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="arrays-and-sequencers"><span class="header-section-number">3.1</span> Arrays and Sequencers</h2>
<p>Sequencer is a tool for organizing and controlling the playback of <code>events</code> in a temporally ordered sequence. This sequence consists of a series of discrete steps, where each step represents a regular time interval and can contain information about event activation or deactivation.</p>
<p>In addition to controlling musical events such as notes, chords, and percussions, a step sequencer can also manage a variety of other events. This includes parameter changes in virtual instruments or audio/video synthesizers, real-time effect automation, lighting control in live performances or multimedia installations, triggering of samples to create patterns and effect sequences, as well as firing MIDI control events to operate external hardware or software.</p>
<p>&nbsp;</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>P1</th>
<th>P2</th>
<th>P3</th>
<th>P4</th>
<th>P5</th>
<th>P6</th>
<th>P7</th>
<th>P8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>x</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>x</td>
</tr>
<tr class="even">
<td>i0</td>
<td>i1</td>
<td>i2</td>
<td>i3</td>
<td>i4</td>
<td>i5</td>
<td>i6</td>
<td>i7</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<ul>
<li>Each cell represents a step in the sequencer.</li>
<li>“P1” to “P8” indicate the steps numbered 1 to 8.</li>
<li>Empty cells represent steps without events or notes.</li>
<li>You can fill each cell with notes or events to represent the desired sequence.</li>
</ul>
<section id="represent-an-8-step-sequencer-using-pseudo-code" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="represent-an-8-step-sequencer-using-pseudo-code"><span class="header-section-number">3.1.1</span> Represent an 8-step sequencer using pseudo code&nbsp;</h3>
<section id="formulation-pseudo-code" class="level4" data-number="3.1.1.1">
<h4 data-number="3.1.1.1" class="anchored" data-anchor-id="formulation-pseudo-code"><span class="header-section-number">3.1.1.1</span> Formulation (pseudo code)</h4>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">Data</span> Structures:</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">-</span> Define a data structure to represent each step of the sequence <span class="er">(</span><span class="ex">e.g.,</span> array, list<span class="kw">)</span><span class="bu">.</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="ex">Variables:</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="ex">-</span> Define an array to store the MIDI note values for each step.</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="ex">-</span> Initialize the sequencer parameters:</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="ex">-</span> CurrentStep = 0</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="ex">-</span> Tempo</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="ex">-</span> NumberOfSteps = 8</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="ex">Algorithm:</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="ex">1.</span> Initialization:</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>   <span class="ex">a.</span> Set CurrentStep to 0.</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>   <span class="ex">b.</span> Ask the user to input the Tempo.</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>   <span class="ex">c.</span> Set NumberOfSteps to 8.</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="ex">2.</span> Loop:</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>   <span class="ex">a.</span> While true:</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>      <span class="ex">i.</span> Calculate the time duration for each step based on the Tempo.</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>      <span class="ex">ii.</span> Play the MIDI note corresponding to the CurrentStep.</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>      <span class="ex">iii.</span> Increment CurrentStep.</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>      <span class="ex">iv.</span> If CurrentStep exceeds NumberOfSteps, reset it to 0.</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>      <span class="ex">v.</span> Wait the calculated duration before moving to the next step.</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>&nbsp;</p>
</section>
</section>
<section id="python-implementation-of-the-8-step-sequencer" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="python-implementation-of-the-8-step-sequencer"><span class="header-section-number">3.1.2</span> Python Implementation of the 8-Step Sequencer</h3>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> mido</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Define a data structure to represent each step in the sequence (8 steps)</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>secuencia <span class="op">=</span> [<span class="va">None</span>] <span class="op">*</span> <span class="dv">8</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Define an array to store MIDI note values for each step</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>notas_midi <span class="op">=</span> [<span class="dv">60</span>, <span class="dv">62</span>, <span class="dv">64</span>, <span class="dv">65</span>, <span class="dv">67</span>, <span class="dv">69</span>, <span class="dv">71</span>, <span class="dv">72</span>]  <span class="co"># C major scale</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Initialize the sequencer parameters</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>paso_actual <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>tempo <span class="op">=</span> <span class="dv">120</span>  <span class="co"># beats per minute</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>num_pasos <span class="op">=</span> <span class="bu">len</span>(secuencia)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Open the virtual MIDI port (use the correct port name, see MIDI_port_name.py)</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>puerto_salida <span class="op">=</span> mido.open_output(<span class="st">'IAC Driver Bus 1'</span>)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Start a loop to continuously play the sequence</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="cf">while</span> <span class="va">True</span>:</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># a. Calculate the time duration for each step based on the tempo</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    duracion_paso <span class="op">=</span> <span class="fl">60.0</span> <span class="op">/</span> tempo  <span class="co"># beat duration in seconds</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># b. "Play" the MIDI note corresponding to the current step</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    nota_actual <span class="op">=</span> <span class="bu">int</span>(notas_midi[paso_actual])  <span class="co"># Ensure it's an integer</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    secuencia[paso_actual] <span class="op">=</span> nota_actual</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Step: </span><span class="sc">{</span>paso_actual<span class="sc">}</span><span class="ss"> --- Note: </span><span class="sc">{</span>secuencia[paso_actual]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Send the MIDI message</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>    mensaje <span class="op">=</span> mido.Message(<span class="st">'note_on'</span>, note<span class="op">=</span>nota_actual)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>    puerto_salida.send(mensaje)</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>    <span class="co"># c. Increment the current step</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>    paso_actual <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>    <span class="co"># d. If current step exceeds the number of steps, reset it to 0</span></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> paso_actual <span class="op">&gt;=</span> num_pasos:</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>        paso_actual <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>    <span class="co"># e. Wait for the calculated duration before moving to the next step</span></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>    time.sleep(duracion_paso)</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Turn off the MIDI note</span></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>    mensaje <span class="op">=</span> mido.Message(<span class="st">'note_off'</span>, note<span class="op">=</span>nota_actual)</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>    puerto_salida.send(mensaje)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This is a simple step sequencer for MIDI. It uses the <code>mido</code> library to send MIDI messages and the <code>time</code> library to control the timing of the sequence.</p>
<p>The script starts by importing the necessary libraries and defining some data structures and initial variables. The <code>secuencia</code> list will hold the sequence of notes to be played, and is initially filled with <code>None</code> values. The <code>notas_midi</code> list contains the MIDI note values for each step in the sequence, representing a C Major scale.</p>
<p>Then, the script initializes some sequencer parameters. The <code>paso_actual</code> variable tracks the current step in the sequence, <code>tempo</code> sets the tempo in beats per minute, and <code>num_pasos</code> stores the total number of steps in the sequence.</p>
<p>The script opens a virtual MIDI output port using <code>mido.open_output()</code>. You may need to change the port name ‘IAC Driver Bus 1’ depending on your system setup.</p>
<p>The main part of the script is a <code>while</code> loop that continuously plays the sequence. For each step, it calculates the step duration based on the tempo, plays the corresponding MIDI note, increments the current step, and waits for the calculated duration before moving to the next step. If the current step exceeds the number of steps in the sequence, it resets to 0. After each note is played, a <code>note_off</code> MIDI message is sent to stop the note.</p>
<p>&nbsp;</p>
</section>
<section id="represent-a-random-sequencer-using-pseudo-code" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="represent-a-random-sequencer-using-pseudo-code"><span class="header-section-number">3.1.3</span> Represent a random sequencer using pseudo code</h3>
<p>&nbsp;</p>
</section>
<section id="random-step-sequencer-implementation" class="level3" data-number="3.1.4">
<h3 data-number="3.1.4" class="anchored" data-anchor-id="random-step-sequencer-implementation"><span class="header-section-number">3.1.4</span> Random Step Sequencer Implementation</h3>
<div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> mido</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> random</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Define a data structure to represent each step of the sequence (8 steps)</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>secuencia <span class="op">=</span> [<span class="va">None</span>] <span class="op">*</span> <span class="dv">8</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Define an array to store MIDI note values for each step</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>notas_midi <span class="op">=</span> [<span class="dv">60</span>, <span class="dv">62</span>, <span class="dv">64</span>, <span class="dv">65</span>, <span class="dv">67</span>, <span class="dv">69</span>, <span class="dv">71</span>, <span class="dv">72</span>]  <span class="co"># C major scale</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Initialize the sequencer parameters</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>paso_actual <span class="op">=</span> random.randint(<span class="dv">0</span>, <span class="dv">7</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>tempo <span class="op">=</span> <span class="dv">120</span>  <span class="co"># beats per minute</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>num_pasos <span class="op">=</span> <span class="bu">len</span>(secuencia)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Open the virtual MIDI port (use the correct port name, see MIDI_port_name.py)</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>puerto_salida <span class="op">=</span> mido.open_output(<span class="st">'IAC Driver Bus 1'</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Start a loop to continuously play the sequence</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="cf">while</span> <span class="va">True</span>:</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># a. Calculate the time duration for each step based on the tempo</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    duracion_paso <span class="op">=</span> <span class="fl">60.0</span> <span class="op">/</span> tempo  <span class="co"># beat duration in seconds</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    <span class="co"># b. "Play" the MIDI note corresponding to the current step</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    nota_actual <span class="op">=</span> <span class="bu">int</span>(notas_midi[paso_actual])  <span class="co"># Ensure it's an integer</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>    secuencia[paso_actual] <span class="op">=</span> nota_actual</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Step: </span><span class="sc">{</span>paso_actual<span class="sc">}</span><span class="ss"> --- Note: </span><span class="sc">{</span>secuencia[paso_actual]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Send the MIDI message</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>    mensaje <span class="op">=</span> mido.Message(<span class="st">'note_on'</span>, note<span class="op">=</span>nota_actual)</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>    puerto_salida.send(mensaje)</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>    <span class="co"># c. Randomize the next step</span></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>    paso_actual <span class="op">=</span> random.randint(<span class="dv">0</span>, <span class="dv">7</span>)</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>    <span class="co"># d. If current step exceeds the number of steps, reset it to 0</span></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> paso_actual <span class="op">&gt;=</span> num_pasos:</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>        paso_actual <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>    <span class="co"># e. Wait for the calculated duration before moving to the next step</span></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>    time.sleep(duracion_paso)</span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Turn off the MIDI note</span></span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>    mensaje <span class="op">=</span> mido.Message(<span class="st">'note_off'</span>, note<span class="op">=</span>nota_actual)</span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a>    puerto_salida.send(mensaje)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This Python script is a modified version of the step-by-step MIDI sequencer from the previous example. The main difference lies in how the current step (<code>paso_actual</code>) is incremented.</p>
<p>In the original script, the current step increased sequentially, creating a predictable pattern of notes. In this modified version, the current step is set to a random integer between 0 and 7 (inclusive). This means that the note sequence will be played in a random order, creating a more unpredictable pattern.</p>
<p>—&nbsp;</p>
</section>
</section>
<section id="piano-phase-steve-reich" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="piano-phase-steve-reich"><span class="header-section-number">3.2</span> Piano Phase (Steve Reich)</h2>
<p><a href="https://payload.cargocollective.com/1/2/82587/8130024/reich_gif_432x432_b_crop_pixel_fixed.gif" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="https://payload.cargocollective.com/1/2/82587/8130024/reich_gif_432x432_b_crop_pixel_fixed.gif" class="img-fluid"></a></p>
<p><a href="./Biblio /SteveReich-PianoPhase.pdf">View Piano Phase Score (S. Reich)</a></p>
<p><em>Piano Phase</em> can be conceived as an algorithm. Starting with two pianos playing the same sequence of notes at the same speed, one of the pianists begins to gradually accelerate their tempo.</p>
<p>When the separation between the notes played by both pianos reaches a fraction of a note’s duration, the phase is shifted and the cycle repeats. This process continues endlessly, creating a hypnotic effect of rhythmic phasing that evolves over time as an infinite sequence of iterations.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://www.nist.gov/sites/default/files/images/2022/01/27/phase-difference.gif" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Phase Difference"><img src="https://www.nist.gov/sites/default/files/images/2022/01/27/phase-difference.gif" class="img-fluid figure-img" alt="Phase Difference"></a></p>
<figcaption>Phase Difference</figcaption>
</figure>
</div>
<div id="fig-cern" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cern-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p></p><div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/Jqoieg0Vqag" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>&nbsp; Performance and visualization of the first section from Steve Reich’s 1967 piece Piano Phase<p></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-cern-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.1
</figcaption>
</figure>
</div>
<section id="piano-phase-process-as-an-algorithm." class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="piano-phase-process-as-an-algorithm."><span class="header-section-number">3.2.1</span> Piano Phase process as an algorithm.</h3>
<section id="algorithm-formulation-pseudo-code" class="level4" data-number="3.2.1.1">
<h4 data-number="3.2.1.1" class="anchored" data-anchor-id="algorithm-formulation-pseudo-code"><span class="header-section-number">3.2.1.1</span> Algorithm Formulation (pseudo code)</h4>
<div class="sourceCode" id="cb4"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="ex">1.</span> Initialize two pianists with the same note sequence.</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="ex">2.</span> Set an initial tempo for both pianists.</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="ex">3.</span> Repeat until the desired phase is reached:</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>     <span class="ex">a.</span> Gradually increase the second pianist<span class="st">'s tempo.</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="st">     b. Compare note positions between both pianists.</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="st">     c. When the separation between the notes reaches a fraction of a note’s duration, invert the phase.</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="st">     d. Continue playback.</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="st">4. Repeat the cycle indefinitely to create a continuous and evolving rhythmic phasing effect.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
</section>
<section id="piano-phase-implementation-in-python-single-sequencer" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="piano-phase-implementation-in-python-single-sequencer"><span class="header-section-number">3.2.2</span> Piano Phase Implementation in Python (single sequencer)</h3>
<div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> mido</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a MIDI note sequence to represent the musical part</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>notas_midi <span class="op">=</span> [<span class="dv">64</span>, <span class="dv">66</span>, <span class="dv">71</span>, <span class="dv">73</span>, <span class="dv">74</span>, <span class="dv">66</span>, <span class="dv">64</span>, <span class="dv">73</span>, <span class="dv">71</span>, <span class="dv">66</span>, <span class="dv">74</span>, <span class="dv">73</span>]  <span class="co"># C major scale</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Open two MIDI output ports</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>puerto_salida1 <span class="op">=</span> mido.open_output(<span class="st">'IAC Driver Bus 1'</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize the sequencer parameters</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>tempo <span class="op">=</span> <span class="bu">int</span>(<span class="dv">120</span> <span class="op">*</span> <span class="dv">4</span>)  <span class="co"># beats per minute</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>duracion_paso <span class="op">=</span> <span class="fl">60.0</span> <span class="op">/</span> tempo  <span class="co"># beat duration in seconds</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Start a loop to continuously play the sequence</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>paso_actual <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="cf">while</span> <span class="va">True</span>:</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># "Play" the MIDI note corresponding to the current step</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    nota_actual <span class="op">=</span> notas_midi[paso_actual]</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    mensaje_on <span class="op">=</span> mido.Message(<span class="st">'note_on'</span>, note<span class="op">=</span>nota_actual)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    mensaje_off <span class="op">=</span> mido.Message(<span class="st">'note_off'</span>, note<span class="op">=</span>nota_actual)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    puerto_salida1.send(mensaje_on)</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    time.sleep(duracion_paso)  <span class="co"># Wait one beat before going to the next step</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    puerto_salida1.send(mensaje_off)  <span class="co"># Send 'note_off' message</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Increment the current step</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    paso_actual <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> paso_actual <span class="op">&gt;=</span> <span class="bu">len</span>(notas_midi):</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>        paso_actual <span class="op">=</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
</section>
<section id="random-melody-generator" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="random-melody-generator"><span class="header-section-number">3.3</span> Random Melody Generator</h2>
<p>This chapter provides a step-by-step explanation of the <a href="../assets/code/sequencers/music-scale-B.pd">music-scale-B.pd</a> Pure Data patch. The patch demonstrates how to generate a melody using a musical scale, store it in an array, and play it back using MIDI.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../assets/images/random_melody.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Random Melody Generator"><img src="../assets/images/random_melody.png" class="img-fluid figure-img" alt="Random Melody Generator"></a></p>
<figcaption>Random Melody Generator</figcaption>
</figure>
</div>
<section id="patch-overview" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="patch-overview"><span class="header-section-number">3.3.1</span> Patch Overview</h3>
<p>The patch is organized into several functional blocks:</p>
<ul>
<li><strong>Scale and Melody Generation</strong></li>
<li><strong>Melody Storage</strong></li>
<li><strong>Playback Control</strong></li>
<li><strong>MIDI Output</strong></li>
</ul>
<p>Below is a simplified diagram of the main data flow:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    A[Scale Input] --&gt; B[Melody Generation]
    B --&gt; C[Store in Array]
    C --&gt; D[Playback Control]
    D --&gt; E[MIDI Output]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<hr>
</section>
<section id="scale-and-melody-generation" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="scale-and-melody-generation"><span class="header-section-number">3.3.2</span> Scale and Melody Generation</h3>
<section id="scale-definition" class="level4" data-number="3.3.2.1">
<h4 data-number="3.3.2.1" class="anchored" data-anchor-id="scale-definition"><span class="header-section-number">3.3.2.1</span> Scale Definition</h4>
<p>The patch starts with a message box containing the scale intervals:</p>
<p><code>0 2 4 5 7 9 11</code></p>
<p>For example, this represents a major scale in semitones accordding to the following mapping:</p>
<div style="width: 50%;">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Note</th>
<th>Interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>C</td>
<td><code>0</code></td>
</tr>
<tr class="even">
<td>C# / Db</td>
<td><code>1</code></td>
</tr>
<tr class="odd">
<td>D</td>
<td><code>2</code></td>
</tr>
<tr class="even">
<td>D# / Eb</td>
<td><code>3</code></td>
</tr>
<tr class="odd">
<td>E</td>
<td><code>4</code></td>
</tr>
<tr class="even">
<td>F</td>
<td><code>5</code></td>
</tr>
<tr class="odd">
<td>F# / Gb</td>
<td><code>6</code></td>
</tr>
<tr class="even">
<td>G</td>
<td><code>7</code></td>
</tr>
<tr class="odd">
<td>G# / Ab</td>
<td><code>8</code></td>
</tr>
<tr class="even">
<td>A</td>
<td><code>9</code></td>
</tr>
<tr class="odd">
<td>A# / Bb</td>
<td><code>10</code></td>
</tr>
<tr class="even">
<td>B</td>
<td><code>11</code></td>
</tr>
</tbody>
</table>
</div>
<p>&nbsp;</p>
<p>The scale is appended to a list and processed to determine its length.</p>
</section>
<section id="random-note-selection" class="level4" data-number="3.3.2.2">
<h4 data-number="3.3.2.2" class="anchored" data-anchor-id="random-note-selection"><span class="header-section-number">3.3.2.2</span> Random Note Selection</h4>
<p>A random number between 0 and 47 is generated (<code>random 48</code>), then shifted up by 60 to get a MIDI note in a typical range.</p>
<p>The note is then mapped to the scale using modulo operations and list indexing.</p>
</section>
<section id="melody-construction" class="level4" data-number="3.3.2.3">
<h4 data-number="3.3.2.3" class="anchored" data-anchor-id="melody-construction"><span class="header-section-number">3.3.2.3</span> Melody Construction</h4>
<p>The patch uses a loop (<code>until</code>, <code>i</code>, <code>+ 1</code>) to generate a sequence of notes.</p>
<p>Each note is calculated based on the scale and stored in a list.</p>
</section>
</section>
<section id="melody-storage" class="level3" data-number="3.3.3">
<h3 data-number="3.3.3" class="anchored" data-anchor-id="melody-storage"><span class="header-section-number">3.3.3</span> Melody Storage</h3>
<p>The generated melody is stored in a Pure Data array called <code>melody</code>.</p>
<p>The array is visualized in the patch for reference.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    MelodyList --&gt;|tabwrite| MelodyArray
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="playback-control" class="level3" data-number="3.3.4">
<h3 data-number="3.3.4" class="anchored" data-anchor-id="playback-control"><span class="header-section-number">3.3.4</span> Playback Control</h3>
<p>A <code>metro</code> object (metronome) triggers playback at a tempo set by a horizontal slider.</p>
<p>Each bang from the metronome advances an index, which reads the next note from the <code>melody</code> array.</p>
</section>
<section id="midi-output" class="level3" data-number="3.3.5">
<h3 data-number="3.3.5" class="anchored" data-anchor-id="midi-output"><span class="header-section-number">3.3.5</span> MIDI Output</h3>
<p>The note value is sent to a <code>makenote</code> object, which creates a MIDI note with velocity and duration.</p>
<p>The note is then sent to the <code>noteout</code> object, which outputs the MIDI note to your system’s MIDI device.</p>
</section>
<section id="step-by-step-data-flow" class="level3" data-number="3.3.6">
<h3 data-number="3.3.6" class="anchored" data-anchor-id="step-by-step-data-flow"><span class="header-section-number">3.3.6</span> Step-by-Step Data Flow</h3>
<ol type="1">
<li><strong>Initialize Scale</strong>: The scale intervals are defined and appended to a list.</li>
<li><strong>Generate Melody</strong>: A loop generates random notes mapped to the scale, storing them in the <code>melody</code> array.</li>
<li><strong>Playback</strong>: A metronome triggers reading from the array, sending notes to MIDI output.</li>
<li><strong>Visualization</strong>: The melody array is displayed as a graph in the patch.</li>
</ol>
</section>
<section id="key-objects-and-their-roles" class="level3" data-number="3.3.7">
<h3 data-number="3.3.7" class="anchored" data-anchor-id="key-objects-and-their-roles"><span class="header-section-number">3.3.7</span> Key Objects and Their Roles</h3>
<div style="width: 50%;">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Object</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>random 48</code></td>
<td>Generates random note indices</td>
</tr>
<tr class="even">
<td><code>+ 60</code></td>
<td>Shifts notes to a higher MIDI octave</td>
</tr>
<tr class="odd">
<td><code>mod 12</code></td>
<td>Maps notes to scale degrees</td>
</tr>
<tr class="even">
<td><code>list-idx</code></td>
<td>Retrieves scale degree from the list</td>
</tr>
<tr class="odd">
<td><code>tabwrite</code></td>
<td>Writes notes to the <code>melody</code> array</td>
</tr>
<tr class="even">
<td><code>metro</code></td>
<td>Controls playback timing</td>
</tr>
<tr class="odd">
<td><code>tabread</code></td>
<td>Reads notes from the <code>melody</code> array</td>
</tr>
<tr class="even">
<td><code>makenote</code></td>
<td>Creates MIDI notes with velocity/duration</td>
</tr>
<tr class="odd">
<td><code>noteout</code></td>
<td>Sends MIDI notes to output</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="diagram-melody-generation-and-playback" class="level3" data-number="3.3.8">
<h3 data-number="3.3.8" class="anchored" data-anchor-id="diagram-melody-generation-and-playback"><span class="header-section-number">3.3.8</span> Diagram: Melody Generation and Playback</h3>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    S[Scale Message] --&gt; L[list Append]
    L --&gt; R[random + Offset]
    R --&gt; M[Modulo/Indexing]
    M --&gt; A[Melody Array]
    A --&gt; P[Playback - metro, tabread]
    P --&gt; MN[makenote]
    MN --&gt; NO[noteout]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="summary" class="level3" data-number="3.3.9">
<h3 data-number="3.3.9" class="anchored" data-anchor-id="summary"><span class="header-section-number">3.3.9</span> Summary</h3>
<p>This patch demonstrates how to algorithmically generate a melody using a musical scale, store it, and play it back via MIDI in Pure Data. The modular structure allows for easy experimentation with different scales, lengths, and playback parameters.</p>
<hr>
<p>Here is the translated version of your Markdown text with the code, links, and format preserved:</p>
<hr>
</section>
</section>
<section id="the-euclidean-algorithm-generates-traditional-musical-rhythms" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="the-euclidean-algorithm-generates-traditional-musical-rhythms"><span class="header-section-number">3.4</span> The Euclidean Algorithm Generates Traditional Musical Rhythms</h2>
<p>Godfried Toussaint (2005)</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://idmmag.com/wp-content/uploads/2019/02/Euclidean-R-1.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Eucliden image"><img src="https://idmmag.com/wp-content/uploads/2019/02/Euclidean-R-1.jpg" class="img-fluid figure-img" alt="Eucliden image"></a></p>
<figcaption>Eucliden image</figcaption>
</figure>
</div>
<p><a href="https://cgm.cs.mcgill.ca/~godfried/publications/banff.pdf">Link to the original article</a></p>
<section id="summary-1" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="summary-1"><span class="header-section-number">3.4.1</span> Summary</h3>
<p>The Euclidean algorithm (as presented in <em>Euclid’s Elements</em>) calculates the greatest common divisor of two given integers. It is shown here that the structure of the Euclidean algorithm can be used to efficiently generate a wide variety of rhythms used as timelines (ostinatos) in sub-Saharan African music in particular, and world music in general. These rhythms, here called <em>Euclidean rhythms</em>, have the property that their onset patterns are distributed as evenly as possible. Euclidean rhythms also find application in nuclear physics accelerators and computer science and are closely related to several families of words and sequences of interest in the combinatorics of words, such as Euclidean strings, with which the rhythms are compared.</p>
</section>
<section id="hypothesis" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="hypothesis"><span class="header-section-number">3.4.2</span> Hypothesis</h3>
<p>Several researchers have observed that rhythms in traditional world music tend to exhibit patterns distributed as regularly or evenly as possible.</p>
<p><strong>Patterns of maximal evenness can be described using the Euclidean algorithm on the greatest common divisor of two integers.</strong></p>
</section>
<section id="patterns-of-maximal-evenness" class="level3" data-number="3.4.3">
<h3 data-number="3.4.3" class="anchored" data-anchor-id="patterns-of-maximal-evenness"><span class="header-section-number">3.4.3</span> Patterns of Maximal Evenness</h3>
<p>The Pattern of Maximal Evenness is a concept used in music theory to create Euclidean rhythms. Euclidean rhythms are rhythmic patterns that evenly distribute beats over a time cycle.</p>
<p>In essence, the Pattern of Maximal Evenness seeks to <strong>distribute a specific number of beats evenly</strong> within a given time span. This is achieved by dividing the time into equal parts and assigning beats to these divisions uniformly.</p>
<p>Example:</p>
<p>x = beat</p>
<p>· = rest</p>
<p>[×· ×· ×· ×· ] → [1 0 1 0 1 0 1 0] (8,4) = 4 beats evenly distributed over 8 pulses</p>
<p>[×· ·×· ·×·] → [1 0 0 1 0 0 1 0] (8,3) = 3 beats evenly distributed over 8 pulses</p>
</section>
<section id="euclidean-algorithm" class="level3" data-number="3.4.4">
<h3 data-number="3.4.4" class="anchored" data-anchor-id="euclidean-algorithm"><span class="header-section-number">3.4.4</span> Euclidean Algorithm</h3>
<p>One of the oldest known algorithms, described in <em>Euclid’s Elements</em> (around 300 BCE) in Proposition 2 of Book VII, now known as the Euclidean algorithm, calculates the greatest common divisor of two given integers.</p>
<p>The idea is very simple. The smaller number is repeatedly subtracted from the larger until the larger becomes zero or smaller than the smaller one, in which case it becomes the remainder. This remainder is then repeatedly subtracted from the smaller number to obtain a new remainder. This process continues until the remainder is zero.</p>
<p>To be more precise, consider the numbers 5 and 8 as an example:</p>
<ul>
<li>First, we divide 8 by 5. This gives a quotient of 1 and a remainder of 3.</li>
<li>Then, we divide 5 by 3, which gives a quotient of 1 and a remainder of 2.</li>
<li>Next, we divide 3 by 2, which gives a quotient of 1 and a remainder of 1.</li>
<li>Finally, we divide 2 by 1, which gives a quotient of 2 and a remainder of 0.</li>
</ul>
<p>The idea is to keep dividing the previous divisor by the remainder obtained in each step until the remainder is 0. When we reach a remainder of 0, the previous divisor is the greatest common divisor of the two numbers.</p>
<p>In short, the process can be seen as a sequence of equations:</p>
<pre class="text"><code>8 = (1)(5) + 3
5 = (1)(3) + 2
3 = (1)(2) + 1
2 = (1)(2) + 0</code></pre>
<p><em>Note: 8 = (1)(5) + 3 means that 8 is divided by 5 once, yielding a quotient of 1 and a remainder of 3.</em></p>
<p>&nbsp;</p>
<p>In essence, it involves successive divisions to find the <code>greatest common divisor</code> of two positive numbers (GCD from now on).</p>
<p>The <code>GCD</code> of two numbers a and b, assuming a &gt; b, is found by first dividing a by b, and obtaining the remainder r.</p>
<p>The GCD of a and b is the same as that of b and r. When we divide a by b, we obtain a quotient c and a remainder r such that:</p>
<p><code>a = c · b + r</code></p>
<p><strong>Examples:</strong></p>
<p>Let’s compute the GCD of 17 and 7.</p>
<p>Since <code>17 = 7 · 2 + 3</code>, then GCD(17, 7) is equal to GCD(7, 3). Again, since 7 = 3 · 2 + 1, then GCD(7, 3) is equal to GCD(3, 1). Here, it is clear that the GCD between 3 and 1 is simply 1. Therefore, the GCD between 17 and 7 is also 1.</p>
<pre class="text"><code>GCD(17,7) = 1

17 = 7 · 2 + 3

7 = 3 · 2 + 1

3 = 1 · 3 + 0</code></pre>
<p>&nbsp;</p>
<p><strong>Another example:</strong></p>
<pre class="text"><code>GCD(8,3) = 1

8 = 3 · 2 + 2

3 = 2 · 1 + 1

2 = 1 · 2 + 0</code></pre>
</section>
<section id="how-does-computing-the-gcd-turn-into-maximally-even-distributed-patterns" class="level3" data-number="3.4.5">
<h3 data-number="3.4.5" class="anchored" data-anchor-id="how-does-computing-the-gcd-turn-into-maximally-even-distributed-patterns"><span class="header-section-number">3.4.5</span> How does computing the GCD turn into maximally even distributed patterns?</h3>
<p>Represent a binary sequence of k ones [1] and n − k zeros [0], where each [0] bit represents a time interval and the ones [1] indicate signal triggers.</p>
<p>The problem then reduces to:</p>
<p><code>Construct a binary sequence of n bits with k ones such that the ones are distributed as evenly as possible among the zeros.</code></p>
<p>A simple case is when k evenly divides n (with no remainder), in which case we should place ones every n/k bits. For example, if n = 16 and k = 4, then the solution is:</p>
<p><code>[1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0]</code></p>
<p>This case corresponds to n and k having a common divisor of k (in this case 4).</p>
<p>More generally, if the greatest common divisor between n and k is g, we would expect the solution to decompose into g repetitions of a sequence of n/g bits.</p>
<p><strong>This connection with greatest common divisors suggests that we could compute a maximally even rhythm using an algorithm like Euclid’s.</strong></p>
<p>&nbsp;</p>
</section>
<section id="example-13-5" class="level3" data-number="3.4.6">
<h3 data-number="3.4.6" class="anchored" data-anchor-id="example-13-5"><span class="header-section-number">3.4.6</span> Example (13, 5)</h3>
<p>Let’s consider a sequence with n = 13 and k = 5.</p>
<p>Since 13 − 5 = 8, we start with a sequence consisting of 5 ones, followed by 8 zeros, which can be thought of as 13 one-bit sequences:</p>
<p>[1 1 1 1 1 0 0 0 0 0 0 0 0]</p>
<p>We begin moving zeros by placing one zero after each one, creating five 2-bit sequences, with three remaining zeros:</p>
<p>[10] [10] [10] [10] [10] [0] [0] [0]</p>
<p><code>13 = 5 · 2 + 3</code></p>
<p>Then we distribute the three remaining zeros similarly, placing a [0] after each [10] sequence:</p>
<p>[100] [100] [100] [10] [10]</p>
<p><code>5 = 3 · 1 + 2</code></p>
<p>We now have three 3-bit sequences, and a remainder of two 2-bit sequences. So we continue the same way, placing one [10] after each [100]:</p>
<p>[10010] [10010] [100]</p>
<p><code>3 = 2 · 1 + 1</code></p>
<p>The process stops when the remainder consists of a single sequence (here, [100]), or we run out of zeros.</p>
<p>The final sequence is, therefore, the concatenation of [10010], [10010], and [100]:</p>
<p><strong>[1 0 0 1 0 1 0 0 1 0 1 0 0]</strong></p>
<p><code>2 = 1 · 2 + 0</code></p>
<p>&nbsp;</p>
</section>
<section id="example-17-7" class="level3" data-number="3.4.7">
<h3 data-number="3.4.7" class="anchored" data-anchor-id="example-17-7"><span class="header-section-number">3.4.7</span> Example (17, 7)</h3>
<p>Suppose we have 17 pulses and want to evenly distribute 7 beats over them.</p>
<p><strong>1.</strong> We align the number of beats and silences (7 ones and 10 zeros):</p>
<p>[1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>1 1 1 1 1 1 1</th>
<th>0 0 0 0 0 0 0 0 0 0</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<p><strong>2.</strong> We form 7 groups, corresponding to the division of 17 by 7; we get 7 groups of <code>[1 0]</code> and 3 remaining zeros <code>[000]</code>, which means the next step forms 3 groups until only one or zero groups remain.</p>
<p>[1 0] [1 0] [1 0] [1 0] [1 0] [1 0] [1 0] [0] [0] [0]</p>
<p><code>17 = 7 · 2 + 3</code></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>1</th>
<th>1</th>
<th>1</th>
<th>1</th>
<th>1</th>
<th>1</th>
<th>1</th>
<th>0 0 0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td></td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<p><strong>3.</strong> Again, this corresponds to dividing 7 by 3. In our case, we are left with only one group and we are done.</p>
<p>&nbsp;</p>
<p>[1 0 0] [1 0 0] [1 0 0] [1 0] [1 0] [1 0] [1 0]</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>1</th>
<th>1</th>
<th>1</th>
<th>1</th>
<th>1</th>
<th>1</th>
<th>1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>0</td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>[1 0 0 1 0] [1 0 1 0 0] [1 0 0 1 0] [1 0]</p>
<p><code>7 = 3 · 2 + 1</code></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>1</th>
<th>1</th>
<th>1</th>
<th>1</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>0</td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>1</td>
<td>1</td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>0</td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<p><strong>4.</strong> Finally, the rhythm is obtained by reading the grouping column by column, from left to right, step by step.</p>
<p><strong><code>[1 0 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0]</code></strong></p>
<p><code>3 = 1 · 3 + 0</code></p>
<p>&nbsp;</p>
</section>
<section id="implementation-in-pure-data---euclidean-sequencer" class="level3" data-number="3.4.8">
<h3 data-number="3.4.8" class="anchored" data-anchor-id="implementation-in-pure-data---euclidean-sequencer"><span class="header-section-number">3.4.8</span> Implementation in Pure Data - Euclidean sequencer</h3>
<pre class="text"><code>(index * hits ) % steps
↓
[&lt; notes]</code></pre>
<p>where:</p>
<p>index = index of the Euclidean series (array)</p>
<p>hits = number of notes to be played</p>
<p>steps = array size</p>
</section>
<section id="references" class="level3" data-number="3.4.9">
<h3 data-number="3.4.9" class="anchored" data-anchor-id="references"><span class="header-section-number">3.4.9</span> References</h3>
<ul>
<li><a href="https://cgm.cs.mcgill.ca/~godfried/publications/banff.pdf">The Euclidean Algorithm Generates Traditional Musical Rhythms</a></li>
<li><a href="https://www.chenalexander.com/Piano-Phase">Piano-Phase</a></li>
</ul>
<hr>
<p>Here is the full English translation of your markdown document, keeping the code, links, and formatting as requested:</p>
<hr>
</section>
</section>
<section id="cellular-automata" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="cellular-automata"><span class="header-section-number">3.5</span> Cellular Automata</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://mathworld.wolfram.com/images/eps-svg/Code0912_450.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Cellular Automaton"><img src="https://mathworld.wolfram.com/images/eps-svg/Code0912_450.svg" class="img-fluid figure-img" alt="Cellular Automaton"></a></p>
<figcaption>Cellular Automaton</figcaption>
</figure>
</div>
<p>A cellular automaton is a mathematical and computational model for a dynamic system that evolves in discrete steps. It is suitable for modeling natural systems that can be described as a massive collection of simple objects interacting locally with each other.</p>
<p>A cellular automaton is a collection of “colored” cells on a grid of specified shape that evolves through a series of discrete time steps according to a set of rules based on the states of neighboring cells. The rules are then applied iteratively over as many time steps as desired.</p>
<p>Cellular automata come in a variety of forms and types. One of the most fundamental properties of a cellular automaton is the type of grid on which it is computed. The simplest such grid is a <code>one-dimensional</code> line. In two dimensions, square, triangular, and hexagonal grids can be considered.</p>
<p>One must also specify the number of colors (or distinct states) <em>k</em> that a cellular automaton can assume. This number is typically an integer, with k=2 (binary, <code>[1]</code> or <code>[0]</code>) being the simplest choice. For a binary automaton, color 0 is commonly referred to as “white” and color 1 as “black”. However, cellular automata with a continuous range of possible values can also be considered.</p>
<p>In addition to the grid on which a cellular automaton resides and the colors its cells can assume, one must also specify the <code>neighborhood</code> over which the cells influence each other.</p>
<section id="one-dimensional-cellular-automata-1dca" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="one-dimensional-cellular-automata-1dca"><span class="header-section-number">3.5.1</span> One-Dimensional Cellular Automata (1DCA)</h3>
<p>The simplest option is <code>"nearest neighbors"</code>, where only the cells directly adjacent to a given cell can influence it at each time step. Two common neighborhoods in the case of a two-dimensional cellular automaton on a square grid are the so-called Moore neighborhood (a square neighborhood) and the von Neumann neighborhood (a diamond-shaped neighborhood).</p>
<p>Cellular automata are considered as a vector. Each component of the vector is called a cell. Each cell is assumed to take only two states:</p>
<ul>
<li>[0] (white)</li>
<li>[1] (black)</li>
</ul>
<p>This type of automaton is known as an elementary one-dimensional cellular automaton (1DCA). A dynamic process is performed, starting from an initial configuration C(0) of each of the cells (stage 0), and at each new stage, the state of each cell is calculated based on the state of the neighboring cells and the cell itself in the previous stage.</p>
</section>
<section id="the-case-of-rule-30" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="the-case-of-rule-30"><span class="header-section-number">3.5.2</span> The Case of Rule 30</h3>
<p>Rule 30 is a binary one-dimensional cellular automaton introduced by <a href="https://en.wikipedia.org/wiki/Stephen_Wolfram">Stephen Wolfram</a> in 1983. It considers an infinite one-dimensional array of cellular automaton cells with only two states, with each cell in some initial state.</p>
<p>At discrete time intervals, each cell changes state spontaneously based on its current state and the state of its two neighbors.</p>
<p>What it consists of:</p>
<ol type="1">
<li><p>Each cell can be in one of two states: alive or dead.</p></li>
<li><p>The next generation of a cell is determined by the current state of the cell and the state of its two neighboring cells.</p></li>
<li><p>There are 8 possible configurations of neighboring states (3^2), and for each, Rule 30 defines whether the cell lives or dies in the next generation.</p></li>
</ol>
<p>For Rule 30, the set of rules that governs the automaton’s next state is:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Configuration</th>
<th>Next State</th>
<th>Binary Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>000</td>
<td>Dead</td>
<td>000</td>
</tr>
<tr class="even">
<td>001</td>
<td>Alive</td>
<td>011</td>
</tr>
<tr class="odd">
<td>010</td>
<td>Dead</td>
<td>000</td>
</tr>
<tr class="even">
<td>011</td>
<td>Alive</td>
<td>011</td>
</tr>
<tr class="odd">
<td>100</td>
<td>Alive</td>
<td>011</td>
</tr>
<tr class="even">
<td>101</td>
<td>Dead</td>
<td>000</td>
</tr>
<tr class="odd">
<td>110</td>
<td>Alive</td>
<td>011</td>
</tr>
<tr class="even">
<td>111</td>
<td>Dead</td>
<td>000</td>
</tr>
</tbody>
</table>
<p>In the following diagram, the top row shows the state of the central cell (cell <em>i</em>) and its two neighboring cells at a given stage, and the bottom row shows the state of the central cell in the next stage.</p>
<p>For example, in the first case of the figure:</p>
<ul>
<li>if the state of a cell at a given stage is <code>[1]</code> (black) and</li>
<li>its two neighbors at that stage are also <code>[1]</code> (black),</li>
<li>then the cell’s state in the next stage will be <code>[0]</code> (white).</li>
</ul>
<p><img src="https://mathworld.wolfram.com/images/eps-svg/ElementaryCARule030_700.svg" class="img-fluid" alt="Rule 30"> <a href="https://mathworld.wolfram.com/CellularAutomaton.html">Source</a></p>
<p>It is called Rule 30 because in binary, 00011110<sub>2</sub> = 30.</p>
<p>Let’s break down the procedure for determining the next state in the 8 combinations:</p>
<p><strong>Input configurations:</strong> Consider the 8 possible input combinations of the three cells (a central cell and its left and right neighbors). Since each cell can be in one of two possible states (0 or 1), the combinations are 000, 001, 010, 011, 100, 101, 110, and 111.</p>
<p><strong>Binary representation of the rule:</strong> Rule 30 is represented by the number 30 in binary, which is 00011110. This binary representation determines the rules for the next state of the central cell for each of the 8 possible combinations.</p>
<p><strong>Bit correspondence:</strong> The 8 bits of the binary representation (00011110) correspond to the 8 input combinations in order. From right to left, the bits represent the next state of the central cell for each input combination.</p>
<p>For example, the least significant bit of 00011110 (the rightmost bit) is 0. This means that when the input combination is 000, the next state of the central cell will be 0.</p>
<p><strong>Next state determination:</strong> For each input combination (e.g., 000, 001, 010, 011, 100, 101, 110, 111), the corresponding bit in the binary representation of Rule 30 [00011110] indicates the next state of the central cell.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Input Configuration</th>
<th>Next State</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>000</td>
<td>0</td>
</tr>
<tr class="even">
<td>001</td>
<td>1</td>
</tr>
<tr class="odd">
<td>010</td>
<td>1</td>
</tr>
<tr class="even">
<td>011</td>
<td>1</td>
</tr>
<tr class="odd">
<td>100</td>
<td>1</td>
</tr>
<tr class="even">
<td>101</td>
<td>0</td>
</tr>
<tr class="odd">
<td>110</td>
<td>0</td>
</tr>
<tr class="even">
<td>111</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>For example, if the input combination is 000 and the corresponding bit in Rule 30 is 0, then the next state of the central cell will be 0.</p>
<p>Therefore, the rules are not arbitrary but are determined by the binary representation of Rule 30, which specifies the next state of the central cell for each input combination of its neighbors.</p>
</section>
<section id="rule-30-implementation-in-python" class="level3" data-number="3.5.3">
<h3 data-number="3.5.3" class="anchored" data-anchor-id="rule-30-implementation-in-python"><span class="header-section-number">3.5.3</span> Rule 30 Implementation in Python</h3>
<div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> rule30(cells):</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Applies Rule 30 to the input cells."""</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    new_cells <span class="op">=</span> np.zeros_like(cells)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    extended_cells <span class="op">=</span> np.concatenate(([cells[<span class="op">-</span><span class="dv">1</span>]], cells, [cells[<span class="dv">0</span>]]))  <span class="co"># Apply periodic boundary conditions</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="bu">len</span>(extended_cells) <span class="op">-</span> <span class="dv">1</span>):</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>        neighborhood <span class="op">=</span> extended_cells[i<span class="op">-</span><span class="dv">1</span>:i<span class="op">+</span><span class="dv">2</span>]</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> np.array_equal(neighborhood, [<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>]) <span class="kw">or</span> np.array_equal(neighborhood, [<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>]) <span class="kw">or</span> <span class="op">\</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>           np.array_equal(neighborhood, [<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>]) <span class="kw">or</span> np.array_equal(neighborhood, [<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>]):</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>            new_cells[i<span class="op">-</span><span class="dv">1</span>] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>            new_cells[i<span class="op">-</span><span class="dv">1</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> new_cells</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> main():</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Initialize the cells</span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>    cells <span class="op">=</span> np.zeros(<span class="dv">100</span>)</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>    cells[<span class="dv">50</span>] <span class="op">=</span> <span class="dv">1</span>  <span class="co"># Start with one cell in the middle</span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Apply Rule 30 for 100 steps</span></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>    history <span class="op">=</span> [cells]</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">100</span>):</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>        cells <span class="op">=</span> rule30(cells)</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>        history.append(cells)</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Display the history as an image</span></span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>    plt.imshow(history, cmap<span class="op">=</span><span class="st">'binary'</span>)</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">"__main__"</span>:</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>    main()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This Python script uses the numpy and matplotlib libraries to simulate and visualize the evolution of a cellular automaton using Rule 30.</p>
<p>The <code>rule30</code> function is the core of this script. It takes a one-dimensional array of cells as input, where each cell is either 0 or 1. The function first creates a new array <code>new_cells</code> with the same shape as the input, filled with zeros. It then extends the input array at both ends to apply periodic boundary conditions, meaning that the first cell is considered a neighbor of the last cell and vice versa.</p>
<p>Next, the function iterates over each cell in the extended array (excluding the added boundary cells). For each cell, it considers the cell and its two neighbors as a neighborhood. If the neighborhood matches one of four specific patterns ([1, 1, 1], [1, 1, 0], [1, 0, 1], or [0, 0, 0]), the corresponding cell in <code>new_cells</code> is set to 0. Otherwise, it is set to 1. This is the implementation of Rule 30. Finally, the function returns the new array of cells.</p>
<p>The main function initializes a one-dimensional array of 100 cells, all set to 0 except the middle cell, which is set to 1. It then applies the <code>rule30</code> function to this array 100 times, storing each resulting array in a list called <code>history</code>. This list is then visualized as a binary image using matplotlib’s <code>imshow</code> function, where each row corresponds to one step in the cellular automaton’s evolution.</p>
<p>The script is designed to run as a standalone program. The line <code>if __name__ == "__main__":</code> ensures that the main function is called only when the script is run directly, not when imported as a module.</p>
</section>
<section id="two-dimensional-cellular-automata-2dca" class="level3" data-number="3.5.4">
<h3 data-number="3.5.4" class="anchored" data-anchor-id="two-dimensional-cellular-automata-2dca"><span class="header-section-number">3.5.4</span> Two-Dimensional Cellular Automata (2DCA)</h3>
<p>Two-dimensional cellular automata are an extension of one-dimensional cellular automata, where cells not only have neighbors to the left and right, but also above and below. This allows modeling of more complex and structurally rich systems, such as two-dimensional phenomena like wave propagation, growth patterns in biology, fire spread, fluid simulation, among others.</p>
<p>Two-dimensional cellular automata (2DCA) are computational models that simulate dynamic systems on a two-dimensional grid.</p>
<p>They consist of:</p>
<ol type="1">
<li><p><em>Cells</em>: Each cell in the grid can have a finite state, such as alive or dead, and can change state according to the automaton’s rules.</p></li>
<li><p><em>Neighborhood</em>: Each cell has a neighborhood, which is a set of adjacent cells that influence its state. The neighborhood can be rectangular, hexagonal, circular, or of any other shape.</p></li>
<li><p><em>Transition rule</em>: The transition rule defines how the state of a cell changes based on its current state and the state of the cells in its neighborhood. The rule can be deterministic or probabilistic.</p></li>
<li><p><em>Evolution</em>: The cellular automaton evolves through iterations. In each iteration, the state of each cell is updated according to the transition rule.</p></li>
</ol>
<p>Here is the full translation of your markdown file into English, with all code, links, and formatting preserved:</p>
<hr>
</section>
<section id="case-study-conways-game-of-life" class="level3" data-number="3.5.5">
<h3 data-number="3.5.5" class="anchored" data-anchor-id="case-study-conways-game-of-life"><span class="header-section-number">3.5.5</span> Case Study: Conway’s Game of Life</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://images.squarespace-cdn.com/content/v1/59413d96e6f2e1c6837c7ecd/1592233649594-7UQA8NZSNXMZWX86FIWN/JB_Game_of_Life.gif?format=2500w" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Game of life"><img src="https://images.squarespace-cdn.com/content/v1/59413d96e6f2e1c6837c7ecd/1592233649594-7UQA8NZSNXMZWX86FIWN/JB_Game_of_Life.gif?format=2500w" class="img-fluid figure-img" alt="Game of life"></a></p>
<figcaption>Game of life</figcaption>
</figure>
</div>
<p><a href="https://www.artnome.com/news/2020/7/12/the-game-of-life-emergence-in-generative-art">Source</a></p>
<p>Conway’s Game of Life, also known simply as the Game of Life, is a cellular automaton devised by British mathematician John Horton Conway in 1970. It is the best-known example of a cellular automaton.</p>
<p>The “game” is actually a zero-player game, meaning its evolution is determined by its initial state, requiring no further input from human players. One interacts with the Game of Life by creating an initial configuration and observing how it evolves.</p>
<p><a href="https://ballyalley.com/articles_and_news/LIFE_Article_%28Scientific_American%29%28October_1970%29.pdf">View Original Article - MATHEMATICAL GAMES - The fantastic combinations of John Conway’s new solitaire game life (Martin Gardner)</a></p>
<p><code>GOL</code> (Game of Life) and <code>CGOL</code> (Conway’s Game of Life) are commonly used acronyms.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://img.youtube.com/vi/xP5-iIeKXE8/0.jpg" class="img-fluid figure-img"></p>
<figcaption>Game of Life</figcaption>
</figure>
</div>
<p><a href="https://www.youtube.com/watch?v=xP5-iIeKXE8">Source</a></p>
<section id="rules" class="level4" data-number="3.5.5.1">
<h4 data-number="3.5.5.1" class="anchored" data-anchor-id="rules"><span class="header-section-number">3.5.5.1</span> Rules</h4>
<p>The universe of the Game of Life is an infinite two-dimensional orthogonal grid of square cells, each of which (at any given time) is in one of two possible states, <code>alive</code> (alternatively “on”) or <code>dead</code> (alternatively “off”). At each time step, the following transitions occur:</p>
<p><strong>The four rules of Conway’s Game of Life:</strong></p>
<p><strong>1. Overpopulation</strong>: Any live cell with more than three live neighbors dies due to overpopulation.</p>
<p><strong>2. Underpopulation</strong>: Any live cell with fewer than two live neighbors dies due to underpopulation.</p>
<p><strong>3. Stability</strong>: Any live cell with two or three live neighbors survives to the next generation.</p>
<p><strong>4. Reproduction</strong>: Any dead cell with exactly three live neighbors becomes a live cell.</p>
<p>&nbsp;</p>
<p>We can also summarize the rules in a table:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 28%">
<col style="width: 17%">
<col style="width: 19%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Rule</th>
<th>Description</th>
<th>Current State</th>
<th>Live Neighbors</th>
<th>Next State</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Overpopulation</td>
<td>Death by overcrowding</td>
<td>Alive</td>
<td>More than 3</td>
<td>Dead</td>
</tr>
<tr class="even">
<td>Underpopulation</td>
<td>Death by isolation</td>
<td>Alive</td>
<td>Fewer than 2</td>
<td>Dead</td>
</tr>
<tr class="odd">
<td>Stability</td>
<td>Survival</td>
<td>Alive</td>
<td>2 or 3</td>
<td>Alive</td>
</tr>
<tr class="even">
<td>Reproduction</td>
<td>Birth</td>
<td>Dead</td>
<td>3</td>
<td>Alive</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<p>Or summarized as:</p>
<p>0 → 3 live neighbors → 1 1 → &lt; 2 or &gt; 3 live neighbors → 0</p>
<p>Where 0 represents a dead cell and 1 a live cell.</p>
<p>&nbsp;</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://the-mvm.github.io/assets/img/posts/20210210/GameOfLife.gif" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Game of life rules"><img src="https://the-mvm.github.io/assets/img/posts/20210210/GameOfLife.gif" class="img-fluid figure-img" alt="Game of life rules"></a></p>
<figcaption>Game of life rules</figcaption>
</figure>
</div>
<p><a href="https://the-mvm.github.io/conways-game-of-life.html">Source</a></p>
<p>&nbsp;</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://d2r55xnwy6nx47.cloudfront.net/uploads/2024/01/TheRulesOfLifebyMerrillSherman_560-Desktop.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Game of life rules"><img src="https://d2r55xnwy6nx47.cloudfront.net/uploads/2024/01/TheRulesOfLifebyMerrillSherman_560-Desktop.svg" class="img-fluid figure-img" alt="Game of life rules"></a></p>
<figcaption>Game of life rules</figcaption>
</figure>
</div>
<p><a href="https://www.quantamagazine.org/maths-game-of-life-reveals-long-sought-repeating-patterns-20240118/">Source</a></p>
<p>The initial pattern constitutes the system’s ‘seed’. The first generation is created by applying the above rules simultaneously to each cell in the seed; births and deaths occur simultaneously, and the discrete moment in which this occurs is sometimes called a step. (In other words, each generation is a pure function of the previous one.) The rules continue to be applied repeatedly to create more generations.</p>
</section>
</section>
<section id="origins" class="level3" data-number="3.5.6">
<h3 data-number="3.5.6" class="anchored" data-anchor-id="origins"><span class="header-section-number">3.5.6</span> Origins</h3>
<p>Conway was interested in a problem presented in the 1940s by renowned mathematician John von Neumann, who was trying to find a hypothetical machine that could build copies of itself and succeeded when he found a mathematical model for such a machine with very complicated rules on a rectangular grid. The Game of Life emerged as Conway’s successful attempt to simplify von Neumann’s ideas.</p>
<p>The game made its first public appearance in the October 1970 issue of Scientific American, in Martin Gardner’s “Mathematical Games” column, under the title “The fantastic combinations of John Conway’s new solitaire game ‘Life’”.</p>
<p>Since its publication, Conway’s Game of Life has attracted significant interest due to the surprising ways patterns can evolve.</p>
<p>Life is an example of emergence and self-organization. It is of interest to physicists, biologists, economists, mathematicians, philosophers, generative scientists, and others, as it shows how complex patterns can emerge from the implementation of very simple rules. The game can also serve as a didactic analogy, used to convey the somewhat counterintuitive notion that “design” and “organization” can spontaneously arise in the absence of a designer.</p>
<p>Conway carefully selected the rules, after considerable experimentation, to meet three criteria:</p>
<ol type="1">
<li><p>There should be no initial pattern for which a simple proof exists that the population can grow without limit.</p></li>
<li><p>There must be initial patterns that appear to grow indefinitely.</p></li>
<li><p>There should be simple initial patterns that evolve and change for a considerable period before ending in one of the following ways:</p>
<ul>
<li>dying out completely (due to overcrowding or becoming too sparse); or</li>
<li>settling into a stable configuration that remains unchanged thereafter, or entering an oscillating phase in which they repeat a cycle endlessly of two or more periods.</li>
</ul></li>
</ol>
</section>
<section id="patterns" class="level3" data-number="3.5.7">
<h3 data-number="3.5.7" class="anchored" data-anchor-id="patterns"><span class="header-section-number">3.5.7</span> Patterns</h3>
<p>Many different types of patterns occur in the Game of Life, including static patterns (“still lifes”), repeating patterns (“oscillators” – a superset of still lifes), and patterns that move across the board (“spaceships”). Common examples of these three classes are shown below, with live cells in black and dead cells in white.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://blog.xojo.com/wp-content/uploads/2022/05/CleanShot-2022-05-02-at-14.25.12@2x.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Gosper glider gun"><img src="https://blog.xojo.com/wp-content/uploads/2022/05/CleanShot-2022-05-02-at-14.25.12@2x.png" class="img-fluid figure-img" alt="Gosper glider gun"></a></p>
<figcaption>Gosper glider gun</figcaption>
</figure>
</div>
<p>Using the provided rules, you can investigate the evolution of simple patterns:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://pi.math.cornell.edu/~lipa/mec/lifep.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="3 cells"><img src="https://pi.math.cornell.edu/~lipa/mec/lifep.png" class="img-fluid figure-img" alt="3 cells"></a></p>
<figcaption>3 cells</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://pi.math.cornell.edu/~lipa/mec/4life2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="4 cells"><img src="https://pi.math.cornell.edu/~lipa/mec/4life2.png" class="img-fluid figure-img" alt="4 cells"></a></p>
<figcaption>4 cells</figcaption>
</figure>
</div>
<p><a href="https://pi.math.cornell.edu/~lipa/mec/lesson6.html">Source</a></p>
<p>Patterns that evolve for long periods before stabilizing are called <code>Methuselahs</code>, the first of which discovered was the <code>R-pentomino</code>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Game_of_life_fpento.svg/164px-Game_of_life_fpento.svg.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="R-pendomino"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Game_of_life_fpento.svg/164px-Game_of_life_fpento.svg.png" class="img-fluid figure-img" alt="R-pendomino"></a></p>
<figcaption>R-pendomino</figcaption>
</figure>
</div>
<p><code>Diehard</code> is a pattern that eventually disappears, rather than stabilizing, after 130 generations, which is believed to be the maximum for initial patterns with seven or fewer cells.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Game_of_life_diehard.svg/324px-Game_of_life_diehard.svg.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14" title="Diehard"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Game_of_life_diehard.svg/324px-Game_of_life_diehard.svg.png" class="img-fluid figure-img" alt="Diehard"></a></p>
<figcaption>Diehard</figcaption>
</figure>
</div>
<p><code>Acorn</code> takes 5,206 generations to produce 633 cells, including 13 escaping gliders.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Game_of_life_acorn.svg/292px-Game_of_life_acorn.svg.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15" title="Acorn"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Game_of_life_acorn.svg/292px-Game_of_life_acorn.svg.png" class="img-fluid figure-img" alt="Acorn"></a></p>
<figcaption>Acorn</figcaption>
</figure>
</div>
<p>Conway originally conjectured that no pattern could grow indefinitely; that is, for any initial configuration with a finite number of live cells, the population could not grow beyond some finite upper bound. The <code>Gosper glider gun</code> pattern produces its first glider in the 15th generation, and another every 30 generations thereafter.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Game_of_life_glider_gun.svg/1000px-Game_of_life_glider_gun.svg.png" class="lightbox" data-gallery="quarto-lightbox-gallery-16" title="Gosper’s glider gun"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Game_of_life_glider_gun.svg/1000px-Game_of_life_glider_gun.svg.png" class="img-fluid figure-img" alt="Gosper’s glider gun"></a></p>
<figcaption>Gosper’s glider gun</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://upload.wikimedia.org/wikipedia/commons/e/e5/Gospers_glider_gun.gif" class="lightbox" data-gallery="quarto-lightbox-gallery-17" title="Gosper glider gun"><img src="https://upload.wikimedia.org/wikipedia/commons/e/e5/Gospers_glider_gun.gif" class="img-fluid figure-img" alt="Gosper glider gun"></a></p>
<figcaption>Gosper glider gun</figcaption>
</figure>
</div>
<p>For many years, this pattern was the smallest known. In 2015, a gun called <code>Simkin glider gun</code> was discovered, which emits a glider every 120 generations, and has fewer live cells but is spread across a larger bounding box at its ends.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Game_of_life_Simkin_glider_gun.svg/1000px-Game_of_life_Simkin_glider_gun.svg.png" class="lightbox" data-gallery="quarto-lightbox-gallery-18" title="Simkin glider gun"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Game_of_life_Simkin_glider_gun.svg/1000px-Game_of_life_Simkin_glider_gun.svg.png" class="img-fluid figure-img" alt="Simkin glider gun"></a></p>
<figcaption>Simkin glider gun</figcaption>
</figure>
</div>
<p><a href="https://medium.com/@swarajkalbande123/conways-game-of-life-life-on-computer-b7edfc85d21a">Source</a> <img src="https://miro.medium.com/v2/resize:fit:1024/format:webp/0*7nf3iKnIaVET4mnr.png" class="img-fluid" alt="Glider Patterns"></p>
<p><a href="https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life">Source</a></p>
</section>
<section id="python-implementation-of-game-of-life" class="level3" data-number="3.5.8">
<h3 data-number="3.5.8" class="anchored" data-anchor-id="python-implementation-of-game-of-life"><span class="header-section-number">3.5.8</span> Python Implementation of Game of Life</h3>
<div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pygame</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>COLOR_BG <span class="op">=</span> (<span class="dv">10</span>, <span class="dv">10</span>, <span class="dv">10</span>,)  <span class="co"># Color de fondo</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>COLOR_GRID <span class="op">=</span> (<span class="dv">40</span>, <span class="dv">40</span>, <span class="dv">40</span>)  <span class="co"># Color de la cuadrícula</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>COLOR_DIE_NEXT <span class="op">=</span> (<span class="dv">170</span>, <span class="dv">170</span>, <span class="dv">170</span>)  <span class="co"># Color de las células que mueren en la siguiente generación</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>COLOR_ALIVE_NEXT <span class="op">=</span> (<span class="dv">255</span>, <span class="dv">255</span>, <span class="dv">255</span>)  <span class="co"># Color de las células que siguen vivas en la siguiente generación</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>pygame.init()</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>pygame.display.set_caption(<span class="st">"conway's game of life"</span>)  <span class="co"># Título de la ventana del juego</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Función para actualizar la pantalla con las células</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> update(screen, cells, size, with_progress<span class="op">=</span><span class="va">False</span>):</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>    updated_cells <span class="op">=</span> np.zeros((cells.shape[<span class="dv">0</span>], cells.shape[<span class="dv">1</span>]))  <span class="co"># Matriz para almacenar las células actualizadas</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> row, col <span class="kw">in</span> np.ndindex(cells.shape):</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>        alive <span class="op">=</span> np.<span class="bu">sum</span>(cells[row<span class="op">-</span><span class="dv">1</span>:row<span class="op">+</span><span class="dv">2</span>, col<span class="op">-</span><span class="dv">1</span>:col<span class="op">+</span><span class="dv">2</span>]) <span class="op">-</span> cells[row, col]  <span class="co"># Cálculo de células vecinas vivas</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>        color <span class="op">=</span> COLOR_BG <span class="cf">if</span> cells[row, col] <span class="op">==</span> <span class="dv">0</span> <span class="cf">else</span> COLOR_ALIVE_NEXT  <span class="co"># Color de la célula actual</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> cells[row, col] <span class="op">==</span> <span class="dv">1</span>:  <span class="co"># Si la célula actual está viva</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> alive <span class="op">&lt;</span> <span class="dv">2</span> <span class="kw">or</span> alive <span class="op">&gt;</span> <span class="dv">3</span>:  <span class="co"># Si tiene menos de 2 o más de 3 vecinos vivos, muere</span></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>                <span class="cf">if</span> with_progress:</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>                    color <span class="op">=</span> COLOR_DIE_NEXT</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>            <span class="cf">elif</span> <span class="dv">2</span> <span class="op">&lt;=</span> alive <span class="op">&lt;=</span> <span class="dv">3</span>:  <span class="co"># Si tiene 2 o 3 vecinos vivos, sigue viva</span></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>                updated_cells[row, col] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>                <span class="cf">if</span> with_progress:</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>                    color <span class="op">=</span> COLOR_ALIVE_NEXT</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:  <span class="co"># Si la célula actual está muerta</span></span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> alive <span class="op">==</span> <span class="dv">3</span>:  <span class="co"># Si tiene exactamente 3 vecinos vivos, revive</span></span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>                updated_cells[row, col] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>                <span class="cf">if</span> with_progress:</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>                    color <span class="op">=</span> COLOR_ALIVE_NEXT</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a>        pygame.draw.rect(screen, color, (col <span class="op">*</span> size, row <span class="op">*</span> size, size <span class="op">-</span> <span class="dv">1</span>, size <span class="op">-</span> <span class="dv">1</span>))  <span class="co"># Dibuja la célula en la pantalla</span></span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> updated_cells  <span class="co"># Devuelve las células actualizadas</span></span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Función principal del programa</span></span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> main():</span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a>    pygame.init()</span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a>    screen <span class="op">=</span> pygame.display.set_mode((<span class="dv">800</span>, <span class="dv">600</span>))  <span class="co"># Crea la ventana del juego</span></span>
<span id="cb11-43"><a href="#cb11-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-44"><a href="#cb11-44" aria-hidden="true" tabindex="-1"></a>    cells <span class="op">=</span> np.zeros((<span class="dv">60</span>, <span class="dv">80</span>))  <span class="co"># Crea una matriz de células muertas</span></span>
<span id="cb11-45"><a href="#cb11-45" aria-hidden="true" tabindex="-1"></a>    screen.fill(COLOR_GRID)  <span class="co"># Rellena la pantalla con el color de la cuadrícula</span></span>
<span id="cb11-46"><a href="#cb11-46" aria-hidden="true" tabindex="-1"></a>    update(screen, cells, <span class="dv">10</span>)  <span class="co"># Actualiza la pantalla con las células</span></span>
<span id="cb11-47"><a href="#cb11-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-48"><a href="#cb11-48" aria-hidden="true" tabindex="-1"></a>    pygame.display.flip()</span>
<span id="cb11-49"><a href="#cb11-49" aria-hidden="true" tabindex="-1"></a>    pygame.display.update()</span>
<span id="cb11-50"><a href="#cb11-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-51"><a href="#cb11-51" aria-hidden="true" tabindex="-1"></a>    running <span class="op">=</span> <span class="va">False</span>  <span class="co"># Variable para controlar si el juego está en ejecución</span></span>
<span id="cb11-52"><a href="#cb11-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-53"><a href="#cb11-53" aria-hidden="true" tabindex="-1"></a>    <span class="cf">while</span> <span class="va">True</span>:</span>
<span id="cb11-54"><a href="#cb11-54" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> Q <span class="kw">in</span> pygame.event.get():</span>
<span id="cb11-55"><a href="#cb11-55" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> Q.<span class="bu">type</span> <span class="op">==</span> pygame.QUIT:  <span class="co"># Si se cierra la ventana, termina el programa</span></span>
<span id="cb11-56"><a href="#cb11-56" aria-hidden="true" tabindex="-1"></a>                pygame.quit()</span>
<span id="cb11-57"><a href="#cb11-57" aria-hidden="true" tabindex="-1"></a>                <span class="cf">return</span></span>
<span id="cb11-58"><a href="#cb11-58" aria-hidden="true" tabindex="-1"></a>            <span class="cf">elif</span> Q.<span class="bu">type</span> <span class="op">==</span> pygame.KEYDOWN:</span>
<span id="cb11-59"><a href="#cb11-59" aria-hidden="true" tabindex="-1"></a>                <span class="cf">if</span> Q.key <span class="op">==</span> pygame.K_SPACE:  <span class="co"># Si se presiona la tecla espacio, se inicia o pausa el juego</span></span>
<span id="cb11-60"><a href="#cb11-60" aria-hidden="true" tabindex="-1"></a>                    running <span class="op">=</span> <span class="kw">not</span> running</span>
<span id="cb11-61"><a href="#cb11-61" aria-hidden="true" tabindex="-1"></a>                    update(screen, cells, <span class="dv">10</span>)</span>
<span id="cb11-62"><a href="#cb11-62" aria-hidden="true" tabindex="-1"></a>                    pygame.display.update()</span>
<span id="cb11-63"><a href="#cb11-63" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> pygame.mouse.get_pressed()[<span class="dv">0</span>]:  <span class="co"># Si se presiona el botón izquierdo del ratón</span></span>
<span id="cb11-64"><a href="#cb11-64" aria-hidden="true" tabindex="-1"></a>                pos <span class="op">=</span> pygame.mouse.get_pos()  <span class="co"># Obtiene la posición del ratón</span></span>
<span id="cb11-65"><a href="#cb11-65" aria-hidden="true" tabindex="-1"></a>                cells[pos[<span class="dv">1</span>] <span class="op">//</span> <span class="dv">10</span>, pos[<span class="dv">0</span>] <span class="op">//</span> <span class="dv">10</span>] <span class="op">=</span> <span class="dv">1</span>  <span class="co"># Marca la célula correspondiente como viva</span></span>
<span id="cb11-66"><a href="#cb11-66" aria-hidden="true" tabindex="-1"></a>                update(screen, cells, <span class="dv">10</span>)</span>
<span id="cb11-67"><a href="#cb11-67" aria-hidden="true" tabindex="-1"></a>                pygame.display.update()</span>
<span id="cb11-68"><a href="#cb11-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-69"><a href="#cb11-69" aria-hidden="true" tabindex="-1"></a>        screen.fill(COLOR_GRID)  <span class="co"># Rellena la pantalla con el color de la cuadrícula</span></span>
<span id="cb11-70"><a href="#cb11-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-71"><a href="#cb11-71" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> running:  <span class="co"># Si el juego está en ejecución</span></span>
<span id="cb11-72"><a href="#cb11-72" aria-hidden="true" tabindex="-1"></a>            cells <span class="op">=</span> update(screen, cells, <span class="dv">10</span>, with_progress<span class="op">=</span><span class="va">True</span>)  <span class="co"># Actualiza las células con progreso</span></span>
<span id="cb11-73"><a href="#cb11-73" aria-hidden="true" tabindex="-1"></a>            pygame.display.update()</span>
<span id="cb11-74"><a href="#cb11-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-75"><a href="#cb11-75" aria-hidden="true" tabindex="-1"></a>        time.sleep(<span class="fl">0.001</span>)  <span class="co"># Espera un breve tiempo para controlar la velocidad del juego</span></span>
<span id="cb11-76"><a href="#cb11-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-77"><a href="#cb11-77" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">"__main__"</span>:</span>
<span id="cb11-78"><a href="#cb11-78" aria-hidden="true" tabindex="-1"></a>    main()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<hr>
<p>This Python script implements Conway’s Game of Life, a cellular automaton devised by British mathematician John Horton Conway. It is a zero-player game, meaning its evolution is determined entirely by its initial state, with no further input required.</p>
<p>The script begins by importing the necessary modules: <code>time</code>, <code>pygame</code> for the graphical interface, and <code>numpy</code> to handle the game grid as a 2D matrix. It then defines color constants used for visualizing the game.</p>
<p>The <code>pygame.init()</code> function is called to initialize all imported Pygame modules. The window title is set to “Conway’s Game of Life” using <code>pygame.display.set_caption()</code>.</p>
<p>The <code>update()</code> function updates the game state and redraws the grid. It takes four arguments: <code>screen</code> (the Pygame surface to draw on), <code>cells</code> (the current game state as a 2D <code>numpy</code> array), <code>size</code> (the pixel size of each cell), and <code>with_progress</code> (a boolean indicating whether to display cells that will change in the next generation).</p>
<p>The function creates a new 2D matrix <code>updated_cells</code> filled with zeros, matching the shape of <code>cells</code>. It then iterates over each cell, calculates the number of live neighbors, and applies the game rules to determine whether the cell will be alive in the next generation. The function draws each cell on the screen using the appropriate color and returns <code>updated_cells</code>.</p>
<p>The <code>main()</code> function initializes Pygame, creates the game window, and initializes the game state as a 2D <code>numpy</code> array of zeros (representing dead cells). It then enters the main loop, which handles Pygame events (such as closing the window or key presses), updates the game state if it is running, and redraws the grid. The game can be started or paused by pressing the spacebar, and cells can be toggled manually by clicking on them.</p>
<p>Finally, the script calls <code>main()</code> to launch the game. Press the spacebar to begin.</p>
</section>
<section id="further-reading" class="level3" data-number="3.5.9">
<h3 data-number="3.5.9" class="anchored" data-anchor-id="further-reading"><span class="header-section-number">3.5.9</span> Further Reading</h3>
<ul>
<li><a href="https://www.artnome.com/news/2020/7/12/the-game-of-life-emergence-in-generative-art">The Game Of Life – Emergence In Generative Art (2020)</a></li>
<li><a href="https://medium.com/@swarajkalbande123/conways-game-of-life-life-on-computer-b7edfc85d21a">Conway’s Game of Life – Life on Computer by Swaraj Kalbande</a></li>
<li><a href="https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life">Wikipedia – Conway’s Game of Life</a></li>
</ul>
</section>
<section id="interactive-websites" class="level3" data-number="3.5.10">
<h3 data-number="3.5.10" class="anchored" data-anchor-id="interactive-websites"><span class="header-section-number">3.5.10</span> Interactive Websites</h3>
<ul>
<li><a href="https://beltoforion.de/en/game_of_life/">John Conway’s Game of Life – An Introduction to Cellular Automata</a></li>
<li><a href="https://conwaylife.com/">conwaylife.com</a></li>
<li><a href="https://nga.178.com/read.php?tid=21761699&amp;rand=998">Cellular Automata Megathread</a></li>
</ul>
<hr>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/playrec.html" class="pagination-link" aria-label="Rec &amp; Play">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Rec &amp; Play</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/synthesis.html" class="pagination-link" aria-label="Synthesis">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Synthesis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 Creative Coding with Pure Data - Ezequiel Abregú
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>